import datetime
import logging
import json
from config import API_KEY, NEARBY_URL, DETAIL_URL
# from request_GoogleAPI import GooglePlacesAPI
# from generate_all_waypoints_dist import GenerateAllWaypointsDist
# from generate_initial_trips import GenerateInitialTrips

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def create_trip_plan(preference):
    preference['type'] = {
        'cafe': ['貓咪咖啡廳'],
        'art_gallery': [],
        # 'restaurant': ['火雞肉飯', '燒烤'],
    }
    '''
    api = GooglePlacesAPI(API_KEY, NEARBY_URL, DETAIL_URL)
    # 請求並儲存所有相符的place_id資料
    all_nearby_places = api.get_nearby_places(preference)
    # 用於儲存所有place_details資料
    all_place_details = []
    for place_id in all_nearby_places:
        place_details = api.get_place_details(place_id)
        processed_details = api.process_place_details(place_details)
        if processed_details:
            all_place_details.append(processed_details)
    # 印出所有符合要求之place_details結果
    print(all_place_details)
    if not all_place_details:
        logger.error("nearby search結果為空")
    '''


def main():
    # 假資料
    preference = {
        'location': '23.4812732, 120.4514065',
        'radius': 20000,
        'maxprice': 4,
        'minprice': 0,
        'type': {
            'cafe': ['貓咪咖啡廳'],
            'art_gallery': [],
            'restaurant': ['火雞肉飯', '燒烤'],
        },
        'est_dep': datetime.datetime(year=2024, month=8, day=29, hour=10, minute=0),
        'est_ret': datetime.datetime(year=2024, month=8, day=30, hour=19, minute=30),
        'dep_day': datetime.time(10, 0),
        'ret_day': datetime.time(16, 0)
    }
    api = GooglePlacesAPI(API_KEY, NEARBY_URL, DETAIL_URL)
    # 請求並儲存所有相符的place_id資料
    all_nearby_places = api.get_nearby_places(preference)
    # 用於儲存所有place_details資料
    for place_id in all_nearby_places:
        place_details = api.get_place_details(place_id)
        api.process_place_details(place_details)
    '''
    all_place_details = []
    for place_id in all_nearby_places:
        place_details = api.get_place_details(place_id)
        processed_details = api.process_place_details(place_details)
        if processed_details:
            all_place_details.append(processed_details)

    # 印出所有符合要求之place_details結果
    print(all_place_details)
    js = json.dumps(all_place_details)
    fp = open('all_place_details.json', 'a')
    for place in all_place_details:
        fp.write(place)
    if not all_place_details:
        logger.error("nearby search結果為空")
    '''

    # 儲存兩點間所有組合並計算距離
    waypoints_dist = GenerateAllWaypointsDist([{'place_id': place['place_id'], 'lat': place['lat'], 'lng': place['lng']} for place in all_place_details], 1.0)
    all_waypoints_dist = waypoints_dist.generate_all_waypoints_dist()
    # 印出所有兩點間距離
    print(all_waypoints_dist)

    all_place_details_test = [
        {'place_id': 'ChIJWwnS2TGVbjQRmDzOmwpNILc',
         'lat': 23.4656562, 'lng': 120.4449676,
         'name': '貓咖啡(7/1起本店將由貓咖轉型成精品咖啡)',
         'formatted_address': '600台灣嘉義市西區民生南路312號',
         'types': ['cafe', 'store', 'point_of_interest', 'food', 'establishment'],
         'formatted_phone_number': '05 236 0085',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.8,
         'user_ratings_total': 275,
         'opening_hours': {'0': [datetime.time(13, 0), datetime.time(21, 0)],
                           '1': [datetime.time(13, 0), datetime.time(21, 0)],
                           '2': [],
                           '3': [datetime.time(13, 0), datetime.time(21, 0)],
                           '4': [datetime.time(13, 0), datetime.time(21, 0)],
                           '5': [datetime.time(13, 0), datetime.time(21, 0)],
                           '6': [datetime.time(13, 0), datetime.time(21, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJGT7_mHuVbjQRM6bZonFysoY',
         'lat': 23.4821101,
         'lng': 120.4601198,
         'name': '喵咪文創咖啡館（無接待0~6歲小孩）最後收客時間20：00',
         'formatted_address': '600台灣嘉義市東區中山路43號',
         'types': ['cafe', 'clothing_store', 'food', 'point_of_interest', 'store', 'establishment'],
         'formatted_phone_number': '05 278 1236',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.9,
         'user_ratings_total': 785,
         'opening_hours': {'0': [datetime.time(12, 0), datetime.time(21, 0)],
                           '1': [datetime.time(12, 0), datetime.time(21, 0)],
                           '2': [],
                           '3': [],
                           '4': [datetime.time(12, 0), datetime.time(21, 0)],
                           '5': [datetime.time(12, 0), datetime.time(21, 0)],
                           '6': [datetime.time(12, 0), datetime.time(21, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJ4ejIPTCUbjQRgE5YCc3IjI4',
         'lat': 23.4767054,
         'lng': 120.448291,
         'name': '嘉義-秘氏咖啡(休假日與菜單請參考IG)',
         'formatted_address': '600台灣嘉義市西區延平街288號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': None,
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.7,
         'user_ratings_total': 324,
         'opening_hours': {'0': [datetime.time(13, 0), datetime.time(21, 0)],
                           '1': [datetime.time(13, 0), datetime.time(21, 0)],
                           '2': [],
                           '3': [],
                           '4': [datetime.time(13, 0), datetime.time(21, 0)],
                           '5': [datetime.time(13, 0), datetime.time(21, 0)],
                           '6': [datetime.time(13, 0), datetime.time(21, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJDfif6TOUbjQRbnU5apxOWR0',
         'lat': 23.4807566,
         'lng': 120.4518163,
         'name': '藏.咖啡 嘉義中山店',
         'formatted_address': '600台灣嘉義市東區中山路233號',
         'types': ['cafe', 'food', 'point_of_interest', 'store', 'establishment'],
         'formatted_phone_number': '05 225 5622',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 1,
         'rating': 4.5,
         'user_ratings_total': 1122,
         'opening_hours': {'0': [datetime.time(9, 0), datetime.time(22, 30)],
                           '1': [datetime.time(9, 0), datetime.time(22, 30)],
                           '2': [datetime.time(9, 0), datetime.time(22, 30)],
                           '3': [datetime.time(9, 0), datetime.time(22, 30)],
                           '4': [datetime.time(9, 0), datetime.time(22, 30)],
                           '5': [datetime.time(9, 0), datetime.time(22, 30)],
                           '6': [datetime.time(9, 0), datetime.time(22, 30)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJ9-a0iMqVbjQRqrlXj3zFgfQ',
         'lat': 23.48162019999999,
         'lng': 120.4586921,
         'name': 'Daisy的雜貨店',
         'formatted_address': '600台灣嘉義市東區維新路73號',
         'types': ['cafe', 'restaurant', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 277 0893',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.6,
         'user_ratings_total': 467,
         'opening_hours': {'0': [datetime.time(13, 0), datetime.time(19, 0)],
                           '1': [datetime.time(13, 0), datetime.time(19, 0)],
                           '2': [datetime.time(13, 0), datetime.time(19, 0)],
                           '3': [datetime.time(13, 0), datetime.time(19, 0)],
                           '4': [],
                           '5': [datetime.time(13, 0), datetime.time(19, 0)],
                           '6': [datetime.time(13, 0), datetime.time(19, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJk5BHbeWVbjQRvRM9kHUbuN8',
         'lat': 23.4769653, 'lng': 120.4476917,
         'name': 'IN COFFEE',
         'formatted_address': '600台灣嘉義市西區忠義街50號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': None,
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 1,
         'rating': 4.6,
         'user_ratings_total': 667,
         'opening_hours': {'0': [datetime.time(13, 0), datetime.time(1, 0)],
                           '1': [datetime.time(15, 0), datetime.time(1, 0)],
                           '2': [datetime.time(15, 0), datetime.time(1, 0)],
                           '3': [datetime.time(15, 0), datetime.time(1, 0)],
                           '4': [datetime.time(15, 0), datetime.time(1, 0)],
                           '5': [datetime.time(15, 0), datetime.time(1, 0)],
                           '6': [datetime.time(13, 0), datetime.time(1, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJy55TlbSVbjQR5S0p7gd76k0',
         'lat': 23.4839121,
         'lng': 120.4630427,
         'name': '簡單咖啡',
         'formatted_address': '600台灣嘉義市東區啟明路277號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 276 5750',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 1,
         'rating': 4.5,
         'user_ratings_total': 98,
         'opening_hours': {'0': [datetime.time(8, 0), datetime.time(17, 30)],
                           '1': [datetime.time(7, 0), datetime.time(18, 0)],
                           '2': [datetime.time(7, 0), datetime.time(18, 0)],
                           '3': [datetime.time(7, 0), datetime.time(18, 0)],
                           '4': [datetime.time(7, 0), datetime.time(18, 0)],
                           '5': [datetime.time(7, 0), datetime.time(18, 0)],
                           '6': [datetime.time(8, 0), datetime.time(17, 30)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJA3VoPP6VbjQRKQTeTZNYr3Q',
         'lat': 23.4797323,
         'lng': 120.4513805,
         'name': '巴倫司康 Baron Scones',
         'formatted_address': '600台灣嘉義市東區公明路297號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 216 0711',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.5,
         'user_ratings_total': 1089,
         'opening_hours': {'0': [datetime.time(12, 0), datetime.time(19, 0)],
                           '1': [datetime.time(12, 0), datetime.time(19, 0)],
                           '2': [datetime.time(12, 0), datetime.time(19, 0)],
                           '3': [datetime.time(12, 0), datetime.time(19, 0)],
                           '4': [datetime.time(12, 0), datetime.time(19, 0)],
                           '5': [datetime.time(12, 0), datetime.time(19, 0)],
                           '6': [datetime.time(12, 0), datetime.time(19, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJofjUHEiUbjQRUP0dDVwDTOw',
         'lat': 23.4740321,
         'lng': 120.4599099,
         'name': 'AMON咖啡所',
         'formatted_address': '600台灣嘉義市東區市宅街22巷5弄5號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 222 2670',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.6,
         'user_ratings_total': 283,
         'opening_hours': {'0': [datetime.time(10, 0), datetime.time(18, 0)],
                           '1': [],
                           '2': [datetime.time(10, 0), datetime.time(18, 0)],
                           '3': [datetime.time(10, 0), datetime.time(18, 0)],
                           '4': [datetime.time(10, 0), datetime.time(18, 0)],
                           '5': [datetime.time(10, 0), datetime.time(18, 0)],
                           '6': [datetime.time(10, 0), datetime.time(18, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJVwRFBQOWbjQRhOvjjEa-hrQ',
         'lat': 23.5302434,
         'lng': 120.4265475,
         'name': '民雄鬼屋咖啡',
         'formatted_address': '621台灣嘉義縣民雄鄉義橋12號',
         'types': ['cafe', 'point_of_interest', 'food', 'establishment'],
         'formatted_phone_number': '05 220 8508',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 1,
         'rating': 4.1,
         'user_ratings_total': 963,
         'opening_hours': {'0': [datetime.time(10, 0), datetime.time(19, 0)],
                           '1': [datetime.time(10, 0), datetime.time(19, 0)],
                           '2': [datetime.time(10, 0), datetime.time(19, 0)],
                           '3': [datetime.time(10, 0), datetime.time(19, 0)],
                           '4': [datetime.time(10, 0), datetime.time(19, 0)],
                           '5': [datetime.time(10, 0), datetime.time(19, 0)],
                           '6': [datetime.time(10, 0), datetime.time(19, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJqx5zi92FbjQRVcemmH98E1k',
         'lat': 23.30641259999999,
         'lng': 120.3211822,
         'name': '漫步日光',
         'formatted_address': '730台灣台南市新營區中山路50號 3 號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '06 632 0882',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.4,
         'user_ratings_total': 398,
         'opening_hours': {'0': [datetime.time(9, 0), datetime.time(19, 0)],
                           '1': [datetime.time(9, 0), datetime.time(19, 0)],
                           '2': [], '3': [datetime.time(9, 0), datetime.time(19, 0)],
                           '4': [datetime.time(9, 0), datetime.time(19, 0)],
                           '5': [datetime.time(9, 0), datetime.time(19, 0)],
                           '6': [datetime.time(9, 0), datetime.time(19, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJmYCBOzSUbjQRPK1TH_Kvl7E',
         'lat': 23.4799528,
         'lng': 120.4548746,
         'name': '提娜多咖啡（早午餐/飯/麵）',
         'formatted_address': '600台灣嘉義市東區公明路167號',
         'types': ['cafe', 'store', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 228 7787',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 1,
         'rating': 4.6,
         'user_ratings_total': 278,
         'opening_hours': {'0': [],
                           '1': [],
                           '2': [datetime.time(8, 0), datetime.time(20, 0)],
                           '3': [datetime.time(8, 0), datetime.time(20, 0)],
                           '4': [datetime.time(8, 0), datetime.time(20, 0)],
                           '5': [datetime.time(8, 0), datetime.time(20, 0)],
                           '6': [datetime.time(8, 0), datetime.time(20, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJdVv-QcuVbjQRgRyFggf7pjM',
         'lat': 23.4859563,
         'lng': 120.454355,
         'name': 'Morikoohii 森 咖啡',
         'formatted_address': '600台灣嘉義市東區共和路199巷1號',
         'types': ['cafe', 'store', 'point_of_interest', 'food', 'establishment'],
         'formatted_phone_number': '05 276 1601#2122',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.5,
         'user_ratings_total': 1126,
         'opening_hours': {'0': [datetime.time(10, 0), datetime.time(18, 0)],
                           '1': [datetime.time(10, 0), datetime.time(18, 0)],
                           '2': [datetime.time(10, 0), datetime.time(18, 0)],
                           '3': [datetime.time(10, 0), datetime.time(18, 0)],
                           '4': [datetime.time(10, 0), datetime.time(18, 0)],
                           '5': [datetime.time(10, 0), datetime.time(18, 0)],
                           '6': [datetime.time(10, 0), datetime.time(18, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJU6G05jKUbjQRKliHNVe0Y-0',
         'lat': 23.4841147,
         'lng': 120.4496869,
         'name': '往前咖啡製作所 / Forward Roasters',
         'formatted_address': '600台灣嘉義市東區興中街205號',
         'types': ['cafe', 'store', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 275 0600',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.5,
         'user_ratings_total': 885,
         'opening_hours': {'0': [datetime.time(9, 30), datetime.time(21, 0)],
                           '1': [datetime.time(9, 30), datetime.time(21, 0)],
                           '2': [],
                           '3': [datetime.time(9, 30), datetime.time(19, 0)],
                           '4': [datetime.time(9, 30), datetime.time(21, 0)],
                           '5': [datetime.time(9, 30), datetime.time(21, 0)],
                           '6': [datetime.time(9, 30), datetime.time(21, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJEaMDozKVbjQRI2Crpui2t4Y',
         'lat': 23.4759909,
         'lng': 120.438864,
         'name': '國王蝴蝶咖啡 Roicafe',
         'formatted_address': '600台灣嘉義市西區中山路616號F棟2樓',
         'types': ['cafe', 'point_of_interest', 'food', 'establishment'],
         'formatted_phone_number': '0903 898 995',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.7,
         'user_ratings_total': 448,
         'opening_hours': {'0': [datetime.time(10, 0), datetime.time(18, 0)],
                           '1': [],
                           '2': [],
                           '3': [datetime.time(10, 0), datetime.time(18, 0)],
                           '4': [datetime.time(10, 0), datetime.time(18, 0)],
                           '5': [datetime.time(10, 0), datetime.time(18, 0)],
                           '6': [datetime.time(10, 0), datetime.time(18, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJ9WYiGTWUbjQR9BxLSmfCqBE',
         'lat': 23.4826782,
         'lng': 120.4563712,
         'name': '慕 珈琲店',
         'formatted_address': '600台灣嘉義市東區安樂街156號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 271 1122',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.8,
         'user_ratings_total': 305,
         'opening_hours': {'0': [datetime.time(12, 0), datetime.time(23, 0)],
                           '1': [datetime.time(12, 0), datetime.time(23, 0)],
                           '2': [datetime.time(12, 0), datetime.time(23, 0)],
                           '3': [],
                           '4': [datetime.time(12, 0), datetime.time(23, 0)],
                           '5': [datetime.time(12, 0), datetime.time(23, 0)],
                           '6': [datetime.time(12, 0), datetime.time(23, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJTRxKYAC-bjQRUeQu8Rk6EOs',
         'lat': 23.5338718,
         'lng': 120.4369985,
         'name': '尼巴熊 Mud Bear Cafe',
         'formatted_address': '621台灣嘉義縣民雄鄉8219號',
         'types': ['cafe', 'point_of_interest', 'food', 'establishment'],
         'formatted_phone_number': '05 221 9828',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.6,
         'user_ratings_total': 329,
         'opening_hours': {'0': [datetime.time(10, 0), datetime.time(19, 0)],
                           '1': [datetime.time(10, 0), datetime.time(19, 0)],
                           '2': [datetime.time(10, 0), datetime.time(19, 0)],
                           '3': [], '4': [datetime.time(10, 0), datetime.time(19, 0)],
                           '5': [datetime.time(10, 0), datetime.time(19, 0)],
                           '6': [datetime.time(10, 0), datetime.time(19, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJyUMxcFKUbjQR5HmLWdiK_zg',
         'lat': 23.47761749999999,
         'lng': 120.4707927,
         'name': 'Fun 輕鬆咖啡美學',
         'formatted_address': '600台灣嘉義市東區大雅路二段497之1號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 271 8123',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.6,
         'user_ratings_total': 113,
         'opening_hours': {'0': [datetime.time(12, 0), datetime.time(22, 0)],
                           '1': [datetime.time(12, 0), datetime.time(22, 0)],
                           '2': [datetime.time(12, 0), datetime.time(22, 0)],
                           '3': [datetime.time(12, 0), datetime.time(22, 0)],
                           '4': [datetime.time(12, 0), datetime.time(22, 0)],
                           '5': [datetime.time(12, 0), datetime.time(23, 0)],
                           '6': [datetime.time(12, 0), datetime.time(23, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJGwCNgziUbjQRaT_u_j-Z_5E',
         'lat': 23.4698272,
         'lng': 120.4585252,
         'name': '玖CAFÉ',
         'formatted_address': '600台灣嘉義市東區興業東路387號',
         'types': ['cafe', 'food', 'point_of_interest', 'establishment'],
         'formatted_phone_number': '05 216 2626',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.4,
         'user_ratings_total': 559,
         'opening_hours': {'0': [datetime.time(13, 0), datetime.time(18, 0)],
                           '1': [datetime.time(13, 0), datetime.time(22, 0)],
                           '2': [datetime.time(13, 0), datetime.time(22, 0)],
                           '3': [datetime.time(13, 0), datetime.time(22, 0)],
                           '4': [],
                           '5': [],
                           '6': [datetime.time(13, 0), datetime.time(22, 0)]},
         'stay_time': datetime.time(1, 30)},
        {'place_id': 'ChIJXWUDSNy9bjQRLhzUbM8ru0Q',
         'lat': 23.5578206,
         'lng': 120.4285224,
         'name': '慢靈魂',
         'formatted_address': '621台灣嘉義縣民雄鄉復興路93號',
         'types': ['cafe', 'point_of_interest', 'food', 'establishment'],
         'formatted_phone_number': '05 226 6832',
         'wheelchair_accessible_entrance': False,
         'business_status': 'OPERATIONAL',
         'price_level': 2,
         'rating': 4.8,
         'user_ratings_total': 430,
         'opening_hours': {'0': [datetime.time(10, 0), datetime.time(19, 0)],
                           '1': [datetime.time(10, 0), datetime.time(19, 0)],
                           '2': [],
                           '3': [datetime.time(10, 0), datetime.time(19, 0)],
                           '4': [datetime.time(10, 0), datetime.time(19, 0)],
                           '5': [datetime.time(10, 0), datetime.time(19, 0)],
                           '6': [datetime.time(10, 0), datetime.time(19, 0)]},
         'stay_time': datetime.time(1, 30)}]

    est_dep_weekday = str(preference['est_dep'].weekday())
    initial_trip = GenerateInitialTrips([{'place_id': place['place_id'], 'opening_hours': place['opening_hours'], 'stay_time': place['stay_time']} for place in all_place_details], preference)
    all_initial_trip = initial_trip.generate_initial_trips()
    # 印出所有行程可能
    print(all_initial_trip)


if __name__ == "__main__":
    main()
